//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingEntities : DbContext
    {
        public ParkingEntities()
            : base("name=ParkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Floor> Floor { get; set; }
        public virtual DbSet<ParkCells> ParkCells { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserMonthPayment> UserMonthPayment { get; set; }
        public virtual DbSet<VehicleType> VehicleType { get; set; }
    }
}
