//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public string license { get; set; }
        public System.DateTime timeEntry { get; set; }
        public Nullable<System.DateTime> timeOut { get; set; }
        public int idPrice { get; set; }
        public int idParkCell { get; set; }
    
        public virtual ParkCells ParkCells { get; set; }
        public virtual Price Price { get; set; }
    }
}
