//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingApi
{
    using System;
    
    public partial class Reporte_Result1
    {
        public Nullable<int> ID { get; set; }
        public string LINCESE { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public Nullable<System.DateTime> TIMEENTRY { get; set; }
        public Nullable<System.DateTime> TIMEOUT { get; set; }
        public Nullable<int> MINUTES_IN_PARKING { get; set; }
        public Nullable<int> MINUTE_PRICE { get; set; }
        public Nullable<int> TOTAL_PRICE { get; set; }
        public string CELL { get; set; }
    }
}
