//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMonthPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMonthPayment()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int id { get; set; }
        public string numberIdentification { get; set; }
        public string name { get; set; }
        public bool state { get; set; }
        public int idParkCells { get; set; }
    
        public virtual ParkCells ParkCell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
